### ISSUE TITLE
Page not Found

### ISSUE THREAD

**Issue by Adarsh0047** [Mohankrish08/KaleidoEO#1]
The link provided in the `README.md` for the weights and biases tracking is not working.
I have attached a screenshot for your reference.
![Screenshot from 2023-12-12 12-04-12](https://github.com/Mohankrish08/KaleidoEO/assets/37295203/27c3a75c-006d-4d8d-a3ca-824223061db2)

**Comment by Mohankrish08** [comment]
Thank you adarsh, I'll fix this

**Comment by Adarsh0047** [comment]
It works now.
